{% set name = "dwclib" %}
{% set version = "2024.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38d07fbe8194731c22dcaff89bf29a59773384b935f6cac7ce721922d941f0d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python >=3.8,<4
    - pip
    - poetry >=0.12
  run:
    - python >=3.8,<4
    - pandas >=1.4
    - dask >=2023
    - sqlalchemy =1.4
    - pyodbc =4.0.39
    - psycopg2 =2.9.3
    - platformdirs >=3.6.0

test:
  imports:
    - dwclib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/larib-data/dwclib
  summary: Python wrapper to DataWarehouse Connect
  description: |
    dwclib is a Python library which enables queries against Philips
    DataWarehouse Connect databases in a simple and fast manner.
    Numerics and Waveform data can be queried and is returned as pandas
    dataframes. Optional dask support is included in the library.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/larib-data/dwclib

extra:
  recipe-maintainers:
    - jaj42
