{% set name = "dwclib" %}
{% set version = "2023.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 028bc58d3ac18a062ae404865e1dccb19d918aac9473855a6c95e427f1bc02d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python >=3.8,<3.11
    - pip
    - poetry >=0.12
  run:
    - python >=3.8,<3.11
    - pandas =1.4
    - numba =0.55.2
    - dask =2022.9.0
    - sqlalchemy =1.4
    - pyodbc =4.0.32
    - psycopg2 =2.9.3

test:
  imports:
    - dwclib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/larib-data/dwclib
  summary: Python wrapper to DataWarehouse Connect
  description: |
    dwclib is a Python library which enables queries against Philips
    DataWarehouse Connect databases in a simple and fast manner.
    Numerics and Waveform data can be queried and is returned as pandas
    dataframes. Optional dask support is included in the library.
    Waveform queries are accelerated with the numba JIT compiler.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/larib-data/dwclib

extra:
  recipe-maintainers:
    - jaj42
